CORRIDA = range(0,12)
PARTICULA = ["e-","gamma","mu-"] 
VARIACION = ["VaryE"]

# Comando establecido para todas las reglas (en especial para archivo run.sh)
shell.prefix("set +uoex pipefail; ")

# Contenedor sandbox a utilizar
container: '../../wcsim'

rule all:
   input:
     expand('../../../../data/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
     expand('../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
     expand('../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
     expand('../../../../data/3_NPZ_event_dump_barrel/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
     expand('../../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION)

rule mac_to_root:
   input:'../../../../data/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac'
   output:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'

   params: 
       i = '/home/compartida/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac',
       o = 'wcs_MCA_{particula}__{l_corrida}_500_MeV.root',
       d = '/home/compartida/2_ROOT/{variacion}/{particula}'    
    
   group: "mygroup"
    
   shell: 
     """
	cd /home/neutrino/software
	source run.sh
        rm {params.o}
        ./WCSim {params.i}
	mv {params.o} {params.d}
     """

rule root_to_event_dump:
   input:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'
   output:'../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
	
   params:
      i = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root",
      o = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz",
      dirO = "/home/compartida/3_NPZ_event_dump/{variacion}/{particula}"
	
   group: "mygroup"

   shell: 
     """
	cd /home/neutrino/software
	source run.sh
	cd /home/WatChMal/DataTools
	time python3 event_dump.py {params.i} 
	mv {params.o} {params.dirO}
     """

rule root_to_event_dump_barrel:
   input:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'
   output:'../../../../data/3_NPZ_event_dump_barrel/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'

   params:
      i = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root",
      o = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz",
      dirO = "/home/compartida/3_NPZ_event_dump_barrel/{variacion}/{particula}"
	
   group: "mygroup"

   shell:
     """
	cd /home/neutrino/software
	source run.sh
	cd /home/WatChMal/DataTools		
	time python3 event_dump_barrel.py {params.i} 
	mv {params.o} {params.dirO}
     """

rule npz_to_image:
   input:'../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
   output:'../../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy'
    
   params:
      i = "/home/compartida/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz",
      o = "IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy",
      dirO = "/home/compartida/4_Imagen_NPZ/{variacion}/{particula}"
	
   group:"mygroup"

   shell:
     """
	python3 /home/Tools_HKM/npz_to_image.py -m /home/compartida/Geometries/IWCD_geometry_mPMT.npy -f {params.i}
        cd ~; mv {params.o} {params.dirO}
     """
