CORRIDA = range(0,12)
shell.prefix("set +uoex pipefail; ")

rule all:
	input:
		expand('../../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root', l_corrida=CORRIDA),
		expand('../../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA)

rule root_to_npz:
	input:'../../../data/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root'
	
	output:'../../../data/3_NPZ_event_dump/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz'
    
	container: "../wcsim-dir"
	
	params:
		i = "/home/compartida/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.root",
        o = "/home/compartida/2_ROOT/VaryE/e-/wcs_MCA_e-__{l_corrida}_500_MeV.npz",
		dirO = "/home/compartida/3_NPZ_event_dump/VaryE/e-"
	
	shell:
		"""
			cd /home/neutrino/software
			source run.sh
			cd /home/WatChMal/DataTools
			time python3 event_dump.py {params.i} 
			mv {params.o} {params.dirO}
		"""
