# Numero de corridas (archivos a procesar)
CORRIDA = range(0,12)
"""
Eliminar o agregar de acuerdo a la particula que quieras ejecutar.
i.e PARTICULA = ["gamma"] o 
	PARTICULA = ["mu-"] o
    PARTICULA = ["e-","gamma","mu-"]
"""
PARTICULA = ["e-"]
VARIACION = ["VaryE"]

# Contenedor sandbox a utilizar
container: '../../wcsim'

rule all:
	input:
		expand('../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
		expand('../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION)

rule npz_to_image:
	input:'../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
	output:'../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy'
    
	params:
		i = "/home/compartida/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz",
		o = "IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy",
		dirO = "/home/compartida/4_Imagen_NPZ/{variacion}/{particula}"
	
	shell:
		"""
			python3 /home/Tools_HKM/npz_to_image.py -m /home/compartida/Geometries/IWCD_geometry_mPMT.npy -f {params.i}
			cd ~; mv {params.o} {params.dirO}
		"""