# Numero de corridas (archivos a procesar)
CORRIDA = range(0,12)
"""
Eliminar o agregar de acuerdo a la particula que quieras ejecutar.
i.e PARTICULA = ["gamma"] o 
	PARTICULA = ["mu-"] o
    PARTICULA = ["e-","gamma","mu-"]
"""
PARTICULA = ["e-","gamma","mu-"]
VARIACION = ["VaryE"]

# Comando establecido para todas las reglas (en especial para archivo run.sh)
shell.prefix("set +uoex pipefail; ")

# Contenedor sandbox a utilizar
container: '../../wcsim'

rule all:
	input:
		expand('../../../../data/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
    	expand('../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
    	expand('../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
		expand('../../../../data/3_NPZ_event_dump_barrel/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION),
    	expand('../../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy', l_corrida=CORRIDA, particula=PARTICULA, variacion=VARIACION)

rule mac_to_root:
    input:'../../../../data/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac'
    output:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'
    
    params: 
       i = '/home/compartida/1_MAC/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.mac',
       o = 'wcs_MCA_{particula}__{l_corrida}_500_MeV.root',
       d = '/home/compartida/2_ROOT/{variacion}/{particula}'    

    shell: 
        """
	        cd /home/neutrino/software
	        source run.sh
            rm {params.o}
            ./WCSim {params.i}
	        mv {params.o} {params.d}
        """

rule root_to_event_dump:
	input:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'
	output:'../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
	
	params:
		i = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root",
		dirO = "/home/compartida/3_NPZ_event_dump/{variacion}/{particula}"
	
	shell:
		"""
			cd /home/neutrino/software
			source run.sh
			cd /home/WatChMal/DataTools
			time python3 event_dump.py {params.i} -d {params.dirO}
		"""

rule root_to_event_dump_barrel:
	input:'../../../../data/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root'
	output:'../../../../data/3_NPZ_event_dump_barrel/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
	
	params:
		i = "/home/compartida/2_ROOT/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.root",
		dirO = "/home/compartida/3_NPZ_event_dump_barrel/{variacion}/{particula}"
	
	shell:
		"""
			cd /home/neutrino/software
			source run.sh
			cd /home/WatChMal/DataTools
			time python3 event_dump_barrel.py {params.i} -d {params.dirO}
		"""

rule npz_to_image:
	input:'../../../../data/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz'
	output:'../../../../data/4_Imagen_NPZ/{variacion}/{particula}/IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy'
    
	params:
		i = "/home/compartida/3_NPZ_event_dump/{variacion}/{particula}/wcs_MCA_{particula}__{l_corrida}_500_MeV.npz",
		o = "IMAGES_wcs_MCA_{particula}__{l_corrida}_500_MeV.npy",
		dirO = "/home/compartida/4_Imagen_NPZ/{variacion}/{particula}"
	
	shell:
		"""
			cd /home/Tools_HKM
			python3 npz_to_image.py -m /home/compartida/Geometry/IWCD_geometry_mPMT.npy -f {params.i}
			mv {params.o} {params.dirO}
        """