# Utilizacion de Singularity
use-singularity: True

# Vinculacion de carpetas de host a contenedor. Cambiar ruta por tu usuario.
singularity-args: "--fakeroot --writable --no-home --bind /home/many/Documentos/WCSim_Snake/WCSim/data:/home/compartida"

# Banderas para ejecutar snakemake
rerun-incomplete: True
printshellcmds: True
keep-going: True
# Cambiar por el número de cores disponibles de tu máquina
cores: 4

